version: "3.8"
services:
  app_database:
    build: ./networks/postgres
    volumes:
      - ./networks/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./networks/postgres/.env

  app_pytorch:
    build: ./networks/pytorch
    tty: true
    volumes:
      - ./networks/pytorch/data:/home
    depends_on:
      - app_database

  app_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./statics:/app/statics
      - ./medias:/app/medias
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - app_database
      - app_pytorch

  app_nginx:
    build: ./networks/nginx
    volumes:
      - ./statics:/app/statics
      - ./medias:/app/medias
    ports:
      - 80:80
    depends_on:
      - app_django